name:    ${project.artifactId}
version: ${project.version}
website: ${project.url}
main:    ${project.groupId}.${project.artifactId}.BukkitPluginMain
author:  SimSonic
softdepend:
  - Vault
  - WorldEdit
  - WorldGuard
  - Residence
commands:
  rscp:
    description: rscPermissions command hub
    usage: Enter /rscp help to see all subcommands
permissions:
  rscp.*:
    description: Gives access to all commands
    default: op
    children:
      rscp.admin: true
  rscp.admin:
    description: Allows you to use all /rscp subcommands
    default: op
    children:
      rscp.admin.lock: true
      rscp.admin.reload: true
      rscp.maintenance.*: true
  rscp.admin.lock:
    description: Allows to enable/disable maintenance modes
    default: op
  rscp.admin.reload:
    description: Allows to reload configuration and database
    default: op
  rscp.maintenance.*:
    description: Allows to connect when server is in any maintenance mode
    default: op
